Feature/implement coupon duration create
zilzu4165/my-coupon pull request #31
Opened 2022-08-24 15:59 UTC by zilzu4165

2022-08-25 04:29 UTC, progresivoJS reviewed
Please check my comments :)

2022-08-25 04:29 UTC, progresivoJS commented on src/main/java/me/zilzu/mycoupon/application/service/Coupon.java
> +    public final Integer duration_in_month;
camelCase 로 작성~

2022-08-25 04:29 UTC, progresivoJS commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +    @DisplayName("쿠폰을 생성할 때 세가지중 하나로 생성되어야 한다. ONCE, REPEATING, FOREVER")
테스트 이름과 아래의 테스트 내용이 다름.

테스트 이름은 세가지 중 하나로 생성되어야하는데,
테스트는 ONCE 하나만 검증중.

2022-08-25 04:29 UTC, progresivoJS commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +        assertThat(retrieve.duration).isEqualTo(coupon.duration);
durationInMonth 는 null 이라는 것도 검증했으면 좋겠음.

2022-08-25 04:29 UTC, progresivoJS commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +        assertThat(retrieve.duration_in_month).isEqualTo(coupon.duration_in_month);
duration 이 REPEATING 이라는것도 검증

2022-08-25 04:30 UTC, progresivoJS commented
추가적으로, REPEATING이 아닌 케이스는 durationInMonth 가 들어오면 error 팅기게도 해야하지않을까?

우리 시스템의 데이터 정합성을 위해.

2022-08-28 20:10 UTC, progresivoJS requested changes
Please check my comments :)

2022-08-28 20:10 UTC, progresivoJS commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +    void test11(CouponDuration duration) {
굳이 @ParameterizedTest 할 필요 있나?

2022-08-28 20:10 UTC, progresivoJS commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +    @EnumSource(value = CouponDuration.class, names = {"ONCE", "FOREVER"})
여전히 테스트 이름과 맞지 않음.

2022-08-28 20:10 UTC, progresivoJS commented on src/main/java/me/zilzu/mycoupon/application/service/CouponService.java
> +        if (!couponRequest.duration.equals(CouponDuration.REPEATING)) {
enum 비교는

```java
if (couponRequest.duration != CouponDuration.REPEATING)
```
처럼 간단하게 가능.

2022-08-28 20:10 UTC, progresivoJS commented on src/main/java/me/zilzu/mycoupon/application/service/CouponService.java
> +            if (null != couponRequest.durationInMonths) {
```java
if (couponRequest.duration != CouponDuration.REPEATING && couponRequest.durationInMonths != null) {
  throw...
}
```

2022-08-28 20:10 UTC, progresivoJS commented on src/main/java/me/zilzu/mycoupon/application/service/CouponService.java
> +            if (null != couponRequest.durationInMonths) {
너무 눈에 들어오지 않는게 아니면, if 중첩문은 합쳐버리는게 나음.

2022-08-28 20:10 UTC, progresivoJS commented on src/main/java/me/zilzu/mycoupon/storage/CouponEntity.java
> +    public final Integer duration_in_month;
변수는 무조건 camelCase.

2022-08-29 09:33 UTC, zilzu4165 commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +    void test11(CouponDuration duration) {
이 테스트를 하기위해 두 가지의 방법이 있는거 같은데 
- CouponRequest에 명시해 REPEATING 이라고 명시해 주는 거랑 
- ParameterizedTest로 REPEATING 값만 명시해주는 거랑 테스트에 대한 목적은 결국 같은데 방법만 다를 뿐
이 중 더 나은 방법이 있다면 무엇이고 이유는 무엇일까요?

2022-08-29 10:48 UTC, progresivoJS commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +    void test11(CouponDuration duration) {
전자가 더 나음.

왜냐면, ParameterizedTest 를 쓰면 거추장스러운 annotation 이 두개나 붙고, 이걸 이해하기 위한 에너지가 더 들어감.
게다가 ParameterizedTest 의 가장 큰 단점인 enum 을 특정하고 싶을 때, string으로 넣어야함. ("REPEATING" 처럼)
만약에 나중에 enum 이름을 refactoring 하면 이 테스트가 깨지기 때문에 좋은 상황이 아님.

따라서 더 간단한 @Test 와 함께 테스트 내에서 REPEATING을 명시하는게 나음.

2022-08-29 10:50 UTC, progresivoJS reviewed
다음번에 수정 부탁

2022-08-29 10:50 UTC, progresivoJS commented on src/main/java/me/zilzu/mycoupon/application/service/CouponService.java
> +        if (couponRequest.duration != CouponDuration.REPEATING && null != couponRequest.durationInMonths) {
다음번엔 couponRequest.durationInMonths != null 로 부탁함.ㅋㅋ

사람이 읽기에 이게 더 편함.

> 만약 couponRequest.durationInMonths 가 null 이 아니면.

2022-08-29 10:51 UTC, progresivoJS approved these changes
엘쥐티엠

2022-08-29 10:51 UTC, progresivoJS commented
마무리하고 머지하면댐~

2022-08-29 13:29 UTC, zilzu4165 commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +    void test11(CouponDuration duration) {
ParameterizedTest는 enum 특정하고 싶을 때 , string으로 넣어야한다,, 그래서 나중에 enum 이름을 refactoring 할 경우 깨진다.
무슨 말인지 이해함

2022-08-29 13:32 UTC, progresivoJS commented on src/test/java/me/zilzu/mycoupon/application/service/CouponCreateTest.java
> +    void test11(CouponDuration duration) {
good

2022-08-29 13:50 UTC, zilzu4165 commented
summary

- enum 비교는 Enum 클래스 안에 equals 메서드에 이미 == 로 구현이 되어 있으므로 '==' 처럼 간단하게 비교가 가능하다.
- 테스트 문맥에 맞는 테스트 코드를 짜야 한다.
- ParameterizedTest 사용시 Enum 프로퍼티 하나만 사용해야 하는 경우라면 또는 그와 대등한 간단한 경우라면, 테스트 메서드의 파라미터로 넘기는 것 보다 직접 테스트코드에 작성하는 것이 코드를 읽는 사람의 가독성, 유지보수 측면에서 더 좋다.

2022-08-30 11:12 UTC, merged